// Generated by scripts/esm.js from src/chrome.js. Do not edit.
import cjs from '../src/chrome.js';

export const {
    mountChrome, chromeTags, chromeConfig, scriptUrls, DEFAULT_BASE,
} = cjs;
export default cjs;
