// Generated by scripts/esm.js from src/frame.js. Do not edit.
import cjs from '../src/frame.js';

export const {
    mountFrame, frameTags, frameConfig, scriptUrls, DEFAULT_BASE,
} = cjs;
export default cjs;
