// Generated by scripts/esm.js from src/limits.js. Do not edit.
import cjs from '../src/limits.js';

export const {
    createActorLimiter, createValkeyLimitStore, defaultActor, WINDOWS,
} = cjs;
export default cjs;
