// Generated by scripts/esm.js from src/media.js. Do not edit.
import cjs from '../src/media.js';

export const {
    createMediaClient, createObjectsClient, mediaUrls, DEFAULT_PUBLIC_ORIGIN,
} = cjs;
export default cjs;
