// Generated by scripts/esm.js from src/realtime.js. Do not edit.
import cjs from '../src/realtime.js';

export const {
    subscribe, createRealtimeClient, parseSSE, DEFAULT_ORIGIN,
} = cjs;
export default cjs;
