// Generated by scripts/esm.js from src/resources.js. Do not edit.
import cjs from '../src/resources.js';

export const {
    parseResourceName, resourceName, resourceNameOf, RESOURCE_KINDS, createResourceIndex, createResourceClient,
} = cjs;
export default cjs;
