// Generated by scripts/esm.js from src/service/index.js. Do not edit.
import cjs from '../src/service/index.js';

export const {
    gracefulStop, within, DRAIN_MS, DEADLINE_MS, ServiceError, createServiceError,
    asServiceError, sendError, run, wrap, jsonBody, privateNoStore,
    jsonErrors, DEFAULT_INTERVAL_MS, HTTP_METHODS, telemetrySample, validateTelemetrySample, telemetrySkipped,
    defaultRouteLabel, createHttpTelemetry, createTelemetryMiddleware, registerSignals, startEventLoopMonitor, stopEventLoopMonitor,
    eventLoopMonitorEnabled, eventLoopLagMs, telemetry, telemetryMiddleware,
} = cjs;
export function createReadiness(...args) { return cjs.createReadiness(...args); }
export function skip(...args) { return cjs.skip(...args); }
export function safeReason(...args) { return cjs.safeReason(...args); }
export function createRegistry(...args) { return cjs.createRegistry(...args); }
export function instrument(...args) { return cjs.instrument(...args); }
export function metricsHandler(...args) { return cjs.metricsHandler(...args); }
export function isLoopbackDirect(...args) { return cjs.isLoopbackDirect(...args); }
export function releaseInfo(...args) { return cjs.releaseInfo(...args); }
export function createRelease(...args) { return cjs.createRelease(...args); }
export function problem(...args) { return cjs.problem(...args); }
export function sendProblem(...args) { return cjs.sendProblem(...args); }
export default cjs;
