// Generated by scripts/esm.js from src/sso/index.js. Do not edit.
import cjs from '../src/sso/index.js';

export const {
    createSsoClient, sanitizeNext, withParam, decodeJwtPayload, fedcmNonceMatches, claimsToUser,
    parseCookies, COOKIES,
} = cjs;
export default cjs;
