// Generated by scripts/esm.js from src/telemetry.js. Do not edit.
import cjs from '../src/telemetry.js';

export const {
    telemetrySample, validateTelemetrySample, createTelemetry,
} = cjs;
export default cjs;
