// Generated by scripts/esm.js from src/testing/index.js. Do not edit.
import cjs from '../src/testing/index.js';

export const {
    createMockPlatform, DEFAULT_ORIGINS, DEFAULT_TOOLS_SATELLITES, DEFAULT_APP_CATALOG,
} = cjs;
export default cjs;
