// Generated by scripts/esm.js from src/testing/index.js. Do not edit.
import cjs from '../src/testing/index.js';

export const {
    createMockPlatform, DEFAULT_ORIGINS,
} = cjs;
export default cjs;
