#!/usr/bin/env node
'use strict';
/**
 * The ESM entry points (esm/*.mjs) re-export the CommonJS modules with named exports. They are
 * checked in (no build step); this script writes them, and test/esm.test.js fails if they are stale.
 *
 *   node scripts/esm.js           write esm/*.mjs
 *   node scripts/esm.js --check   exit 1 if any file differs
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ENTRIES = {
    'index.mjs': '../index.js',
    'core.mjs': '../src/core/index.js',
    'auth.mjs': '../src/auth/index.js',
    'auth-browser.mjs': '../src/auth/browser.js',
    'registry.mjs': '../src/registry.js',
    'identity.mjs': '../src/identity.js',
    'modules.mjs': '../src/modules.js',
    'events.mjs': '../src/events.js',
    'realtime.mjs': '../src/realtime.js',
    'media.mjs': '../src/media.js',
    'community.mjs': '../src/community.js',
    'jobs.mjs': '../src/jobs.js',
    'tools.mjs': '../src/tools.js',
    'projects.mjs': '../src/projects.js',
    'vip.mjs': '../src/vip.js',
    'testing.mjs': '../src/testing/index.js',
};

function render(file, target) {
    const names = Object.keys(require(path.join(ROOT, 'esm', target)));
    const lines = [];
    for (let i = 0; i < names.length; i += 6) lines.push(`    ${names.slice(i, i + 6).join(', ')},`);
    return `// Generated by scripts/esm.js from ${target.slice(3)}. Do not edit.\n`
        + `import cjs from '${target}';\n\n`
        + `export const {\n${lines.join('\n')}\n} = cjs;\nexport default cjs;\n`;
}

function main() {
    const check = process.argv.includes('--check');
    let stale = 0;
    for (const [file, target] of Object.entries(ENTRIES)) {
        const out = render(file, target);
        const p = path.join(ROOT, 'esm', file);
        const have = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null;
        if (have === out) continue;
        stale++;
        if (check) console.error(`stale: esm/${file}`);
        else fs.writeFileSync(p, out);
    }
    if (check && stale) process.exit(1);
}

if (require.main === module) main();
module.exports = { ENTRIES, render };
