#!/usr/bin/env node
'use strict';
/**
 * The ESM entry points (esm/*.mjs) re-export the CommonJS modules with named exports. They are
 * checked in (no build step); this script writes them, and test/esm.test.js fails if they are stale.
 *
 *   node scripts/esm.js           write esm/*.mjs
 *   node scripts/esm.js --check   exit 1 if any file differs
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ENTRIES = {
    'index.mjs': '../index.js',
    'core.mjs': '../src/core/index.js',
    'auth.mjs': '../src/auth/index.js',
    'auth-browser.mjs': '../src/auth/browser.js',
    'registry.mjs': '../src/registry.js',
    'identity.mjs': '../src/identity.js',
    'modules.mjs': '../src/modules.js',
    'events.mjs': '../src/events.js',
    'sso.mjs': '../src/sso/index.js',
    'realtime.mjs': '../src/realtime.js',
    'media.mjs': '../src/media.js',
    'community.mjs': '../src/community.js',
    'bot.mjs': '../src/bot.js',
    'search.mjs': '../src/search.js',
    'limits.mjs': '../src/limits.js',
    'govern.mjs': '../src/govern.js',
    'placement.mjs': '../src/placement.js',
    'usage.mjs': '../src/usage.js',
    'telemetry.mjs': '../src/telemetry.js',
    'cost.mjs': '../src/cost.js',
    'runtime.mjs': '../src/runtime.js',
    'storage.mjs': '../src/storage.js',
    'commerce.mjs': '../src/commerce.js',
    'delivery.mjs': '../src/delivery.js',
    'node.mjs': '../src/node.js',
    'db.mjs': '../src/db/index.js',
    'valkey.mjs': '../src/valkey.js',
    'cache.mjs': '../src/cache.js',
    'queue.mjs': '../src/queue.js',
    'pubsub.mjs': '../src/pubsub.js',
    'chat.mjs': '../src/chat.js',
    'ai.mjs': '../src/ai.js',
    'jobs.mjs': '../src/jobs.js',
    'tools.mjs': '../src/tools.js',
    'projects.mjs': '../src/projects.js',
    'geo.mjs': '../src/geo.js',
    'openre.mjs': '../src/openre.js',
    'vip.mjs': '../src/vip.js',
    'frame.mjs': '../src/frame.js',
    'service.mjs': '../src/service/index.js',
    'testing.mjs': '../src/testing/index.js',
};

/**
 * A getter on the CommonJS exports is a lazy re-export (openvibe-sdk/service's openvibe-shared and openvibe-contracts
 * functions): destructuring would load its package on import, so the ESM name is a function that reads it on call.
 */
function render(file, target) {
    const mod = require(path.join(ROOT, 'esm', target));
    const all = Object.keys(mod);
    const names = all.filter((n) => !Object.getOwnPropertyDescriptor(mod, n).get);
    const lazy = all.filter((n) => Object.getOwnPropertyDescriptor(mod, n).get);
    const lines = [];
    for (let i = 0; i < names.length; i += 6) lines.push(`    ${names.slice(i, i + 6).join(', ')},`);
    return `// Generated by scripts/esm.js from ${target.slice(3)}. Do not edit.\n`
        + `import cjs from '${target}';\n\n`
        + `export const {\n${lines.join('\n')}\n} = cjs;\n`
        + lazy.map((n) => `export function ${n}(...args) { return cjs.${n}(...args); }\n`).join('')
        + `export default cjs;\n`;
}

function main() {
    const check = process.argv.includes('--check');
    let stale = 0;
    for (const [file, target] of Object.entries(ENTRIES)) {
        const out = render(file, target);
        const p = path.join(ROOT, 'esm', file);
        const have = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null;
        if (have === out) continue;
        stale++;
        if (check) console.error(`stale: esm/${file}`);
        else fs.writeFileSync(p, out);
    }
    if (check && stale) process.exit(1);
}

if (require.main === module) main();
module.exports = { ENTRIES, render };
